/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The ranked analyst queue
         * @description Ordered by `queue_priority ASC, combined_score DESC, id ASC` unless `sort` overrides it. `sort=queue` is the contract order and what the demo shows; the other keys are inspection tools, not alternative rankings. Maximum page size 200.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One alert: flow, signature, model and combined evidence
         * @description An alert no detector flagged is a valid response, not a 404.
         */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign an alert to the caller, or unassign it */
        post: operations["assignAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record an analyst verdict
         * @description Invokes the guardrails and the family learning in one transaction. The response carries the full adjustment chain so the caller can show what bound the change. A rejected adjustment is a 200 with `action: rejected`, not an error — the verdict was recorded and the score was protected.
         */
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/feedback-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every verdict on one alert, oldest first
         * @description Append-only. An amendment is a new record citing the one it supersedes; `effective` names the verdict currently in force.
         */
        get: operations["getFeedbackHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The alert's notes thread, oldest first */
        get: operations["listAlertNotes"];
        put?: never;
        /**
         * Add a note to the alert
         * @description Append-only: a correction is a new note.
         */
        post: operations["addAlertNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/score-adjustment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current adjustment chain for one alert */
        get: operations["getScoreAdjustment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertRef}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim, work, resolve, dismiss, release or reopen an alert
         * @description Workflow, not judgement: never moves a score or invokes a guardrail. Working an alert makes the caller its owner when it has none. A refused transition is a 409. Writes an ALERT_STATUS_CHANGE audit entry.
         */
        post: operations["changeAlertStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The append-only audit trail */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/guardrails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current guardrail settings */
        get: operations["getGuardrailConfig"];
        /**
         * Change guardrail settings (system_admin only)
         * @description A rationale is required: the audit entry records why, not just what. An analyst role receives 403.
         */
        put: operations["updateGuardrailConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/breakdowns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top talkers, verdict and status mix, guardrail actions, capture-time histogram
         * @description Recorded flows: the histogram is capture time, not a live rate.
         */
        get: operations["getDashboardBreakdowns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue composition and feedback activity */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detection/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a batch detection run
         * @description Detection is an offline batch (D3), never inline in a request.
         */
        post: operations["startDetectionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/ip/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the recorded flows say about one IP address */
        get: operations["getIpEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Committed three-arm evaluation runs, newest first
         * @description Read from evaluation/three-arm/runs/, not from a database: each arm runs against its own database copy.
         */
        get: operations["listEvaluationRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Three-arm comparison for one evaluation run
         * @description Deltas may be negative and must be rendered as measured.
         */
        get: operations["getEvaluationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs/{runId}/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-class detection metrics for one evaluation run
         * @description Identical across all three arms by construction — feedback never changes the detection decision.
         */
        get: operations["getEvaluationDetectionMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pre-registered evaluation scenarios */
        get: operations["listEvaluationScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Actor
         * @description Who did something. The demo's users are seeded; S18 replaces this with a real principal.
         */
        Actor: {
            /**
             * Displayname
             * @default null
             */
            displayName: string | null;
            /**
             * Role
             * @default null
             */
            role: ("security_analyst" | "system_admin" | "evaluator") | null;
            /**
             * Userid
             * @description Internal id; null for system actions
             * @default null
             */
            userId: number | null;
        };
        /**
         * AlertDetail
         * @description ``GET /api/alerts/{alertRef}`` — the summary plus the four panels and the family.
         */
        AlertDetail: {
            alert: components["schemas"]["AlertSummary"];
            /** @default null */
            currentFeedback: components["schemas"]["FeedbackRecord"] | null;
            evidence: components["schemas"]["EvidencePanel"];
            family: components["schemas"]["FamilyPanel"];
            /** Feedbackcount */
            feedbackCount: number;
            flow: components["schemas"]["FlowPanel"];
            ml: components["schemas"]["MlPanel"];
            signature: components["schemas"]["SignaturePanel"];
        };
        /**
         * AlertNotes
         * @description ``GET /api/alerts/{alertRef}/notes`` — the whole thread, oldest first.
         */
        AlertNotes: {
            /**
             * Alertref
             * Format: uuid
             */
            alertRef: string;
            /** Notes */
            notes?: components["schemas"]["NoteOut"][];
        };
        /**
         * AlertSummary
         * @description One row of the analyst queue.
         *
         *     Everything here is what a triage decision needs at a glance. Anything requiring a second
         *     thought belongs in the detail response, not in a 50-row list.
         */
        AlertSummary: {
            /**
             * Alertref
             * Format: uuid
             * @description Public identity. Row ids are never exposed
             */
            alertRef: string;
            /**
             * Attackcategory
             * @description The class the system assigned; null when nothing flagged it
             * @default null
             */
            attackCategory: ("Benign" | "Botnet" | "Brute Force" | "DDoS" | "DoS" | "Infiltration" | "Port Scan" | "Web Attack") | null;
            /**
             * Combinedscore
             * @description Operational: what analyst feedback moves
             */
            combinedScore: number;
            /** Confidence */
            confidence: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Detectionscore
             * @description Immutable: what detection produced
             */
            detectionScore: number;
            /** Dstip */
            dstIp: string;
            /** Dstport */
            dstPort: number;
            /**
             * Evidenceclass
             * @description What evidence exists. Never changes, and is never sorted on
             * @enum {string}
             */
            evidenceClass: "corroborated" | "signature_override" | "ml_only" | "none";
            /**
             * Familysize
             * @description Alerts in this alert's family, itself included; 0 when it has no family
             * @default 0
             */
            familySize: number;
            /**
             * Flowtime
             * @description When the flow was captured, as the dataset recorded it (capture-local, no timezone)
             * @default null
             */
            flowTime: string | null;
            /**
             * Hasfeedback
             * @description Whether any analyst verdict has been recorded
             */
            hasFeedback: boolean;
            /** Iscritical */
            isCritical: boolean;
            /**
             * Matchedruleids
             * @description Empty for an ML-only or unflagged alert
             */
            matchedRuleIds?: string[];
            /**
             * @description Who is working the alert; null when nobody owns it
             * @default null
             */
            owner: components["schemas"]["Actor"] | null;
            /** Protocol */
            protocol: string;
            /**
             * Queueclass
             * @description The band the alert sits in now; feedback moves this (Q24)
             * @enum {string}
             */
            queueClass: "tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none";
            /**
             * Queuepriority
             * @description Sort key for queue_class; lower is higher
             */
            queuePriority: number;
            /** Requiresreview */
            requiresReview: boolean;
            /**
             * Severity
             * @enum {string}
             */
            severity: "Critical" | "High" | "Medium" | "Low" | "Informational";
            /**
             * Sourcerecordid
             * @description The flow's id in its source dataset (e.g. AL-00478): the short, stable name an analyst reads aloud in a demo. An identifier, not a label (S12)
             */
            sourceRecordId: string;
            /** Srcip */
            srcIp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "claimed" | "in_progress" | "resolved" | "dismissed";
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ArmResultOut */
        ArmResultOut: {
            /** Arm */
            arm: string;
            /** Criticalfloorbreaches */
            criticalFloorBreaches: number;
            /**
             * Criticalpreservationrate
             * @default null
             */
            criticalPreservationRate: number | null;
            /** Falsepositivesintop50 */
            falsePositivesInTop50: number;
            /** Feedback */
            feedback: boolean;
            /** Guardrailactions */
            guardrailActions?: {
                [key: string]: number;
            };
            /** Guardrailpass */
            guardrailPass: boolean;
            /** Guardrails */
            guardrails: boolean;
            /** Meanranktruepositives */
            meanRankTruePositives: number;
            /** Mrrtruepositives */
            mrrTruePositives: number;
            /** Precisionat50 */
            precisionAt50: number;
            /** Signatureoverridealerts */
            signatureOverrideAlerts: number;
            /** Verdicts */
            verdicts: number;
        };
        /**
         * AssignRequest
         * @description ``POST /api/alerts/{alertRef}/assign``.
         *
         *     `me` assigns the caller's demo user (the auth stub: there is one demo user per role); `null`
         *     unassigns. Assigning a `new` alert claims it; unassigning a `claimed` alert releases it.
         */
        AssignRequest: {
            /** Owner */
            owner: "me" | null;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /**
         * AuditEntryOut
         * @description One append-only audit record. ``UPDATE`` and ``DELETE`` raise at the database (NFR-02/03).
         */
        AuditEntryOut: {
            actor: components["schemas"]["Actor"];
            /**
             * Alertref
             * @default null
             */
            alertRef: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Details
             * @default null
             */
            details: {
                [key: string]: unknown;
            } | null;
            /** Eventid */
            eventId: number;
            /**
             * Eventtype
             * @enum {string}
             */
            eventType: "LOGIN" | "LOGOUT" | "DETECTION_RUN" | "FEEDBACK" | "FEEDBACK_AMEND" | "GUARDRAIL_INTERVENTION" | "GUARDRAIL_REJECTION" | "SIMILAR_ALERT_LEARNING" | "ALERT_STATUS_CHANGE" | "ALERT_DUPLICATE" | "CONFIG_CHANGE" | "RULE_CREATE" | "RULE_UPDATE" | "MODEL_STATUS_CHANGE" | "EVALUATION_RUN";
            /**
             * Rationale
             * @default null
             */
            rationale: string | null;
        };
        /** ClassMetrics */
        ClassMetrics: {
            /** F1 */
            f1: number;
            /** Fnr */
            fnr: number;
            /** Fpr */
            fpr: number;
            /** Precision */
            precision: number;
            /** Predicted */
            predicted: number;
            /** Recall */
            recall: number;
            /** Support */
            support: number;
        };
        /**
         * DashboardBreakdowns
         * @description ``GET /api/dashboard/breakdowns`` — top talkers, verdict and status mix, guardrail actions,
         *     and flow volume by capture hour (console rebuild B4).
         *
         *     These are **recorded** flows: the histogram shows when the traffic was captured, not a live rate.
         */
        DashboardBreakdowns: {
            /** Flowtimehistogram */
            flowTimeHistogram?: components["schemas"]["TimeBucket"][];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /**
             * Guardrailinterventions
             * @description Interventions by guardrail code
             */
            guardrailInterventions?: {
                [key: string]: number;
            };
            /** Statusmix */
            statusMix?: {
                [key: string]: number;
            };
            /** Topdestinationips */
            topDestinationIps?: components["schemas"]["TopValue"][];
            /** Topdestinationports */
            topDestinationPorts?: components["schemas"]["TopValue"][];
            /** Topsourceips */
            topSourceIps?: components["schemas"]["TopValue"][];
            /**
             * Verdictmix
             * @description Verdicts currently in force, by category
             */
            verdictMix?: {
                [key: string]: number;
            };
        };
        /**
         * DashboardSummary
         * @description ``GET /api/dashboard/summary`` — the analyst's landing view.
         */
        DashboardSummary: {
            /**
             * Alertsmovedbyfeedback
             * @description Alerts whose combined_score or queue_class differs from detection
             * @default 0
             */
            alertsMovedByFeedback: number;
            /** Byattackcategory */
            byAttackCategory?: {
                [key: string]: number;
            };
            /** Byevidenceclass */
            byEvidenceClass?: {
                [key: string]: number;
            };
            /** Byqueueclass */
            byQueueClass?: components["schemas"]["QueueBandCount"][];
            /** Byseverity */
            bySeverity?: {
                [key: string]: number;
            };
            /** Feedbackevents */
            feedbackEvents: number;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Guardrailinterventions */
            guardrailInterventions: number;
            /** Requiresreview */
            requiresReview: number;
            /**
             * Runid
             * @default null
             */
            runId: number | null;
            /** Tier2Candidates */
            tier2Candidates: number;
            /** Totalalerts */
            totalAlerts: number;
        };
        /**
         * DetectionRunRequest
         * @description ``POST /api/detection/run``. Detection is an offline batch (D3), never inline in a request:
         *     the endpoint starts a run and returns its handle.
         */
        DetectionRunRequest: {
            /**
             * Limit
             * @description First N flows in timestamp order
             * @default null
             */
            limit: number | null;
            /**
             * Sample
             * @description Source CSV path; defaults to the committed demo sample
             * @default null
             */
            sample: string | null;
            /**
             * Seed
             * @default null
             */
            seed: number | null;
        };
        /** DetectionRunSummary */
        DetectionRunSummary: {
            /**
             * Alerts
             * @default 0
             */
            alerts: number;
            /** Byevidenceclass */
            byEvidenceClass?: {
                [key: string]: number;
            };
            /** Byqueueclass */
            byQueueClass?: {
                [key: string]: number;
            };
            /**
             * Completedat
             * @default null
             */
            completedAt: string | null;
            /** Datasetid */
            datasetId: number;
            /**
             * Explanationscomputed
             * @default true
             */
            explanationsComputed: boolean;
            /**
             * Flows
             * @default 0
             */
            flows: number;
            /** Modelversion */
            modelVersion: string;
            /** Rulesetversion */
            ruleSetVersion: string;
            /** Runid */
            runId: number;
            /**
             * Seed
             * @default null
             */
            seed: number | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "aborted";
        };
        /**
         * EntityIp
         * @description ``GET /api/entities/ip/{ip}`` — what the recorded flows say about one address (B5).
         */
        EntityIp: {
            /** Alerts */
            alerts: number;
            /** Asdestination */
            asDestination: number;
            /** Assource */
            asSource: number;
            /** Byattackcategory */
            byAttackCategory?: {
                [key: string]: number;
            };
            /** Byqueueclass */
            byQueueClass?: {
                [key: string]: number;
            };
            /**
             * Firstseen
             * @description Earliest capture time
             * @default null
             */
            firstSeen: string | null;
            /** Flagged */
            flagged: number;
            /** Ip */
            ip: string;
            /**
             * Lastseen
             * @description Latest capture time
             * @default null
             */
            lastSeen: string | null;
            /** Topdestinationports */
            topDestinationPorts?: components["schemas"]["TopValue"][];
            /** Toppeers */
            topPeers?: components["schemas"]["TopValue"][];
            /** Verdictmix */
            verdictMix?: {
                [key: string]: number;
            };
        };
        /**
         * ErrorBody
         * @description The body of every non-2xx response. One shape, so a client has one error path.
         */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable code, e.g. NOT_FOUND
             */
            code: string;
            /**
             * Detail
             * @description Field-level context; never internal ids or SQL
             * @default null
             */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Human-readable, safe to display
             */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * EvaluationComparison
         * @description ``GET /api/evaluation/runs/{runId}`` — the three arms and their deltas.
         *
         *     **Deltas may be negative, and the screen must render them as measured.** S15's first run showed
         *     precision@50 falling 1.000 → 0.980 and a benign alert reaching rank 1. Reporting only the
         *     favourable direction would rebuild the exit criterion plan v0.3 struck out.
         */
        EvaluationComparison: {
            /** Arms */
            arms?: components["schemas"]["ArmResultOut"][];
            /**
             * Commit
             * @default null
             */
            commit: string | null;
            /**
             * Deltas
             * @description B_minus_A, C_minus_A, C_minus_B
             */
            deltas?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Detectionmetricsidenticalacrossarms
             * @description Proof that feedback reordered the queue and did not touch the detector
             */
            detectionMetricsIdenticalAcrossArms: boolean;
            /**
             * Guardrailsprevented
             * @description As measured. Zero everywhere means the guardrails did not bind on this sequence — a result, not a failed run
             */
            guardrailsPrevented?: {
                [key: string]: unknown;
            };
            /** Movement */
            movement?: {
                [key: string]: {
                    [key: string]: components["schemas"]["MovementGroup"];
                } | null;
            };
            /** Preregistration */
            preregistration?: {
                [key: string]: unknown;
            };
            /** Runid */
            runId: string;
            /**
             * Sequencedigest
             * @default null
             */
            sequenceDigest: string | null;
            /** Sequencelength */
            sequenceLength: number;
        };
        /**
         * EvaluationDetectionMetrics
         * @description ``GET /api/evaluation/runs/{runId}/detection`` — the confusion view S14 renders.
         */
        EvaluationDetectionMetrics: {
            /** Alerts */
            alerts: number;
            /** Attacks */
            attacks: number;
            flaggedVsBenign: components["schemas"]["ClassMetrics"];
            /** Macrof1 */
            macroF1: number;
            /** Perclass */
            perClass?: {
                [key: string]: components["schemas"]["ClassMetrics"];
            };
            /** Precisionat */
            precisionAt?: components["schemas"]["PrecisionAtK"][];
            saturation: components["schemas"]["SaturationMetrics"];
            signatureOverride: components["schemas"]["SignatureOverridePreservation"];
        };
        /**
         * EvaluationRunOut
         * @description ``GET /api/evaluation/runs`` — one committed three-arm run, so the evaluator can find it.
         *
         *     Added at S14: the runs live in `evaluation/three-arm/runs/`, not in any database, so without a
         *     listing the evaluator would need a run id typed from a terminal.
         */
        EvaluationRunOut: {
            /**
             * Arms
             * @description Arm names, in run order
             */
            arms?: string[];
            /**
             * Commit
             * @default null
             */
            commit: string | null;
            /** Detectionmetricsidenticalacrossarms */
            detectionMetricsIdenticalAcrossArms: boolean;
            /** Preregistration */
            preregistration?: {
                [key: string]: unknown;
            };
            /** Runid */
            runId: string;
            /** Sequencelength */
            sequenceLength: number;
        };
        /** EvaluationScenarioOut */
        EvaluationScenarioOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Datasetid */
            datasetId: number;
            /** Guardrailsactive */
            guardrailsActive: boolean;
            /** Modelversion */
            modelVersion: string;
            /** Name */
            name: string;
            /** Preregistration */
            preregistration?: {
                [key: string]: unknown;
            };
            /** Rulesetversion */
            ruleSetVersion: string;
            /** Scenarioid */
            scenarioId: number;
            /**
             * Sequencedigest
             * @default null
             */
            sequenceDigest: string | null;
            /**
             * Sequencelength
             * @default 0
             */
            sequenceLength: number;
        };
        /**
         * EvidencePanel
         * @description Panel 4 — how the two were combined, in words the analyst can repeat in a handover.
         */
        EvidencePanel: {
            /**
             * Agreement
             * @description True when rule and model both flagged this flow
             */
            agreement: boolean;
            /**
             * Evidenceclass
             * @enum {string}
             */
            evidenceClass: "corroborated" | "signature_override" | "ml_only" | "none";
            /** Explanation */
            explanation: string;
            /**
             * Fusionscheme
             * @default null
             */
            fusionScheme: string | null;
            /**
             * Queueclass
             * @enum {string}
             */
            queueClass: "tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none";
            /**
             * Tier2Candidate
             * @description Would be escalated to Tier 2 (Q25 — the demo shows the marker; automatic escalation is post-demo)
             */
            tier2Candidate: boolean;
        };
        /**
         * FamilyEffect
         * @description What this verdict taught the alerts like it. Zero members moved is a normal answer — the
         *     gate needs three verdicts before it opens.
         */
        FamilyEffect: {
            /**
             * Familykey
             * @default null
             */
            familyKey: string | null;
            /**
             * Gateopen
             * @default false
             */
            gateOpen: boolean;
            /**
             * Gatereason
             * @default null
             */
            gateReason: string | null;
            /** Guardrailinterventions */
            guardrailInterventions?: {
                [key: string]: number;
            };
            /**
             * Membersmoved
             * @default 0
             */
            membersMoved: number;
        };
        /**
         * FamilyPanel
         * @description What the alert's family has learned (S7b) — why an alert nobody touched may have moved.
         */
        FamilyPanel: {
            /**
             * Agreementratio
             * @default null
             */
            agreementRatio: number | null;
            /**
             * Appliedadjustment
             * @default 0
             */
            appliedAdjustment: number;
            /**
             * Appliedoffset
             * @default 0
             */
            appliedOffset: number;
            /**
             * Dominantcategory
             * @default null
             */
            dominantCategory: ("confirm_true_positive" | "mark_false_positive" | "mark_expected_activity") | null;
            /**
             * Familykey
             * @default null
             */
            familyKey: string | null;
            /**
             * Gateopen
             * @default false
             */
            gateOpen: boolean;
            /**
             * Gatereason
             * @default null
             */
            gateReason: string | null;
            /**
             * Members
             * @default 0
             */
            members: number;
            /**
             * Note
             * @description Why this alert's score differs from its detection score when it has no verdict of its own
             * @default null
             */
            note: string | null;
        };
        /**
         * FeedbackHistory
         * @description ``GET /api/alerts/{alertRef}/feedback-history`` — oldest first, amendments included.
         */
        FeedbackHistory: {
            /**
             * Alertref
             * Format: uuid
             */
            alertRef: string;
            /**
             * @description The verdict currently in force; feedback does not stack
             * @default null
             */
            effective: components["schemas"]["FeedbackRecord"] | null;
            /** Events */
            events?: components["schemas"]["FeedbackRecord"][];
        };
        /**
         * FeedbackRecord
         * @description One recorded verdict. Append-only: an amendment is a new record citing the one it replaces.
         */
        FeedbackRecord: {
            actor: components["schemas"]["Actor"];
            adjustment: components["schemas"]["ScoreAdjustment"];
            /**
             * Amendedfrom
             * @description The verdict this one supersedes, if any
             * @default null
             */
            amendedFrom: number | null;
            /**
             * Category
             * @enum {string}
             */
            category: "confirm_true_positive" | "mark_false_positive" | "mark_expected_activity" | "needs_investigation" | "escalate";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Feedbackref
             * @description Sequence of the event, for ordering in the history view
             */
            feedbackRef: number;
            /**
             * Note
             * @default null
             */
            note: string | null;
        };
        /**
         * FeedbackRequest
         * @description ``POST /api/alerts/{alertRef}/feedback``.
         *
         *     Five scoring categories. ``duplicate`` is deliberately absent — it is a *queue action*
         *     (link to the original, suppress from the active queue), not a score change, and the documents'
         *     "six categories" folds the two together (`deviations.md` A6).
         */
        FeedbackRequest: {
            /**
             * Category
             * @enum {string}
             */
            category: "confirm_true_positive" | "mark_false_positive" | "mark_expected_activity" | "needs_investigation" | "escalate";
            /**
             * Note
             * @default null
             */
            note: string | null;
        };
        /**
         * FeedbackResponse
         * @description What the analyst sees the moment they submit.
         */
        FeedbackResponse: {
            alert: components["schemas"]["AlertSummary"];
            /**
             * Auditeventids
             * @description Audit entries this one action wrote
             */
            auditEventIds?: number[];
            family: components["schemas"]["FamilyEffect"];
            feedback: components["schemas"]["FeedbackRecord"];
        };
        /**
         * FlowPanel
         * @description Panel 1 — what the flow was.
         */
        FlowPanel: {
            /** Bytes */
            bytes: number;
            /** Dstip */
            dstIp: string;
            /** Dstport */
            dstPort: number;
            /** Durationseconds */
            durationSeconds: number;
            /**
             * Features
             * @description The CICFlowMeter vector under corrected-release column names
             */
            features?: {
                [key: string]: number | string | null;
            };
            /** Packets */
            packets: number;
            /** Protocol */
            protocol: string;
            /**
             * Sourcerecordid
             * @description The flow's id in its source dataset. The evaluation's only join to ground truth; exposed for traceability, and it carries no label
             */
            sourceRecordId: string;
            /** Srcip */
            srcIp: string;
            /** Srcport */
            srcPort: number;
        };
        /**
         * GuardrailConfig
         * @description ``GET /api/config/guardrails``.
         */
        GuardrailConfig: {
            /** Settings */
            settings?: components["schemas"]["GuardrailSetting"][];
        };
        /**
         * GuardrailConfigUpdate
         * @description ``PUT /api/config/guardrails`` — **role-gated to `system_admin`** (the stub checks the
         *     header; S18 makes it real).
         *
         *     Every field is optional; omitted settings are left alone. Values are validated against the same
         *     ranges `GuardrailPolicy` enforces, so an invalid configuration is refused here rather than
         *     discovered when an analyst's feedback behaves strangely.
         */
        GuardrailConfigUpdate: {
            /**
             * Criticalalertfloor
             * @default null
             */
            criticalAlertFloor: number | null;
            /**
             * Criticalalertthreshold
             * @default null
             */
            criticalAlertThreshold: number | null;
            /**
             * Infiltrationalertfloor
             * @default null
             */
            infiltrationAlertFloor: number | null;
            /**
             * Maxfeedbackincrease
             * @default null
             */
            maxFeedbackIncrease: number | null;
            /**
             * Maxfeedbackreduction
             * @default null
             */
            maxFeedbackReduction: number | null;
            /**
             * Rationale
             * @description Required: the audit entry records why, not just what
             */
            rationale: string;
        };
        /**
         * GuardrailInterventionOut
         * @description One guardrail that acted, named so the UI can explain it rather than show a bare number.
         */
        GuardrailInterventionOut: {
            /**
             * Appliedvalue
             * @default null
             */
            appliedValue: number | null;
            /**
             * Code
             * @enum {string}
             */
            code: "non_finite_adjustment_rejected" | "maximum_negative_adjustment_capped" | "maximum_increase_capped" | "critical_alert_floor" | "infiltration_alert_floor" | "signature_ml_disagreement_review_preserved" | "signature_override_feedback_immune" | "score_range_clamped";
            /** Configuredvalue */
            configuredValue: number;
            /** Explanation */
            explanation: string;
            /**
             * Originalvalue
             * @default null
             */
            originalValue: number | null;
        };
        /** GuardrailSetting */
        GuardrailSetting: {
            /** Configkey */
            configKey: string;
            /** Configvalue */
            configValue: number;
            /**
             * Description
             * @default null
             */
            description: string | null;
            /**
             * Updatedat
             * @default null
             */
            updatedAt: string | null;
        };
        /**
         * MlPanel
         * @description Panel 3 — what the model said, and why (NFR-01).
         *
         *     ``additivityPassed`` is not decoration: it is the check that the explanation actually explains
         *     this prediction. 5,000/5,000 pass on the demo sample.
         */
        MlPanel: {
            /**
             * Additivitypassed
             * @default null
             */
            additivityPassed: boolean | null;
            /**
             * Basevalue
             * @default null
             */
            baseValue: number | null;
            /**
             * Explanationstatus
             * @default null
             */
            explanationStatus: string | null;
            /**
             * Modelversion
             * @default null
             */
            modelVersion: string | null;
            /**
             * Note
             * @description Empty-state text when no prediction exists
             * @default null
             */
            note: string | null;
            /**
             * Predictedclass
             * @default null
             */
            predictedClass: ("Benign" | "Botnet" | "Brute Force" | "DDoS" | "DoS" | "Infiltration" | "Port Scan" | "Web Attack") | null;
            /**
             * Probability
             * @default null
             */
            probability: number | null;
            /**
             * Rawmargin
             * @default null
             */
            rawMargin: number | null;
            /** Topopposing */
            topOpposing?: components["schemas"]["ShapFeature"][];
            /** Topsupporting */
            topSupporting?: components["schemas"]["ShapFeature"][];
        };
        /**
         * MovementGroup
         * @description ``adjusted`` is the system acting; ``rankChanged`` includes drift caused by others moving.
         *     Leakage is measured by ``adjusted`` in the ``unrelated`` group, never by rank.
         */
        MovementGroup: {
            /** Adjusted */
            adjusted: number;
            /** Alerts */
            alerts: number;
            /** Attackspromoted */
            attacksPromoted: number;
            /** Bandchanged */
            bandChanged: number;
            /** Benigndemoted */
            benignDemoted: number;
            /** Benignpromoted */
            benignPromoted: number;
            /**
             * Bestrankreachedbyabenignalert
             * @default null
             */
            bestRankReachedByABenignAlert: number | null;
            /** Demoted */
            demoted: number;
            /** Meanrankchange */
            meanRankChange: number;
            /** Promoted */
            promoted: number;
            /** Rankchanged */
            rankChanged: number;
            /** Scorechanged */
            scoreChanged: number;
        };
        /** NoteOut */
        NoteOut: {
            author: components["schemas"]["Actor"];
            /** Body */
            body: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Noteid */
            noteId: number;
        };
        /**
         * NoteRequest
         * @description ``POST /api/alerts/{alertRef}/notes``. Append-only: a correction is a new note.
         */
        NoteRequest: {
            /** Body */
            body: string;
        };
        /**
         * PageInfo
         * @description Where in the queue this page sits.
         *
         *     Offset paging, deliberately: the queue is a ranked list an analyst works down, so a cursor
         *     would buy nothing and cost the ability to jump to a position.
         */
        PageInfo: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Returned
             * @description Items in this response
             */
            returned: number;
            /**
             * Total
             * @description Total items matching the filters, before paging
             */
            total: number;
        };
        /** PrecisionAtK */
        PrecisionAtK: {
            /** Attacks */
            attacks: number;
            /** Falsepositives */
            falsePositives: number;
            /** K */
            k: number;
            /** Precision */
            precision: number;
        };
        /** QueueBandCount */
        QueueBandCount: {
            /** Count */
            count: number;
            /**
             * Queueclass
             * @enum {string}
             */
            queueClass: "tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none";
            /** Requiresreview */
            requiresReview: number;
        };
        /**
         * RuleMatchPanel
         * @description One rule that fired.
         */
        RuleMatchPanel: {
            /**
             * Attackcategory
             * @default null
             */
            attackCategory: ("Benign" | "Botnet" | "Brute Force" | "DDoS" | "DoS" | "Infiltration" | "Port Scan" | "Web Attack") | null;
            /**
             * Matchedconditions
             * @description Field, operator and observed value, per clause
             */
            matchedConditions?: {
                [key: string]: unknown;
            }[];
            /** Name */
            name: string;
            /**
             * Rationale
             * @default null
             */
            rationale: string | null;
            /** Ruleid */
            ruleId: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "Critical" | "High" | "Medium" | "Low";
        };
        /**
         * SaturationMetrics
         * @description Why a promotion can be inert: where a band sits at the ceiling the formula has no headroom
         *     and order falls to the `id ASC` tie-break. 975 of 996 on the demo sample.
         */
        SaturationMetrics: {
            /** Atmaximumscore */
            atMaximumScore: number;
            /** Distinctscoresamongflagged */
            distinctScoresAmongFlagged: number;
            /** Flaggedalerts */
            flaggedAlerts: number;
            /** Shareatmaximum */
            shareAtMaximum: number;
        };
        /**
         * ScoreAdjustment
         * @description The chain S12 visualises: original → requested → bound → actual → final.
         *
         *     Also returned on its own by ``GET /api/alerts/{alertRef}/score-adjustment``, so the screen can
         *     re-read it without re-submitting a verdict.
         */
        ScoreAdjustment: {
            /**
             * Action
             * @description applied | capped | rejected
             * @enum {string}
             */
            action: "applied" | "capped" | "rejected";
            /** Actualdelta */
            actualDelta: number;
            /**
             * Detectionscore
             * @description The immutable base every adjustment measures from
             */
            detectionScore: number;
            /** Interventions */
            interventions?: components["schemas"]["GuardrailInterventionOut"][];
            /**
             * Queueclassafter
             * @enum {string}
             */
            queueClassAfter: "tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none";
            /**
             * Queueclassbefore
             * @enum {string}
             */
            queueClassBefore: "tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none";
            /** Requesteddelta */
            requestedDelta: number;
            /** Requiresreview */
            requiresReview: boolean;
            /** Scoreafter */
            scoreAfter: number;
            /** Scorebefore */
            scoreBefore: number;
            /**
             * Summary
             * @description One sentence stating what happened and what bound it
             */
            summary: string;
        };
        /** ShapFeature */
        ShapFeature: {
            /**
             * Direction
             * @description supports_prediction | opposes_prediction
             */
            direction: string;
            /** Featurename */
            featureName: string;
            /**
             * Featurevalue
             * @default null
             */
            featureValue: number | string | null;
            /** Shapcontribution */
            shapContribution: number;
        };
        /**
         * SignatureOverridePreservation
         * @description Invariant I3, reported separately as the plan requires — including when the database holds
         *     no such alert, in which case the rate is null and the note says why.
         */
        SignatureOverridePreservation: {
            /** Alerts */
            alerts: number;
            /** Changed */
            changed: number;
            /**
             * Note
             * @default null
             */
            note: string | null;
            /**
             * Preservationrate
             * @default null
             */
            preservationRate: number | null;
        };
        /**
         * SignaturePanel
         * @description Panel 2 — what the rules said. ``matched`` empty is the ML-only empty state.
         */
        SignaturePanel: {
            /** Matched */
            matched?: components["schemas"]["RuleMatchPanel"][];
            /**
             * Note
             * @description Empty-state text for the panel, e.g. 'no rule matched (ML-only alert)'
             * @default null
             */
            note: string | null;
            /**
             * Rulesetversion
             * @default null
             */
            ruleSetVersion: string | null;
            /**
             * Severityscore
             * @description Highest matched rule severity, 0-1; null when nothing matched
             * @default null
             */
            severityScore: number | null;
        };
        /**
         * StatusChangeRequest
         * @description ``POST /api/alerts/{alertRef}/status``.
         *
         *     Working an alert (`claimed`, `in_progress`) makes the caller its owner when it has none;
         *     returning it to `new` releases it; a closed alert (`resolved`, `dismissed`) can only be reopened
         *     to `in_progress`. A refused transition is a 409.
         */
        StatusChangeRequest: {
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "claimed" | "in_progress" | "resolved" | "dismissed";
        };
        /** TimeBucket */
        TimeBucket: {
            /**
             * Bucket
             * @description Capture-local hour, e.g. 2018-02-14 12:00
             */
            bucket: string;
            /** Count */
            count: number;
            /** Flagged */
            flagged: number;
        };
        /**
         * TopValue
         * @description One value and how often it occurs, e.g. an IP address or a destination port.
         */
        TopValue: {
            /** Count */
            count: number;
            /**
             * Flagged
             * @description Of these, alerts a detector flagged (band is not none)
             */
            flagged: number;
            /** Value */
            value: string;
        };
        /** TriageResponse */
        TriageResponse: {
            alert: components["schemas"]["AlertSummary"];
            /**
             * Auditeventid
             * @description The ALERT_STATUS_CHANGE entry this wrote
             */
            auditEventId: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAlerts: {
        parameters: {
            query?: {
                /** @description null */
                limit?: number;
                /** @description null */
                offset?: number;
                /** @description Default `queue` is the contract order: queue_priority ASC, combined_score DESC, id ASC */
                sort?: "queue" | "combined_score" | "detection_score" | "created_at" | "severity";
                /** @description null */
                direction?: "asc" | "desc";
                /** @description Filter to these queue bands */
                queueClass?: ("tier2_candidate" | "corroborated" | "signature_override" | "ml_only" | "none")[] | null;
                /** @description Filter to these evidence classes. Reported, never sorted on */
                evidenceClass?: ("corroborated" | "signature_override" | "ml_only" | "none")[] | null;
                /** @description null */
                severity?: ("Critical" | "High" | "Medium" | "Low" | "Informational")[] | null;
                /** @description null */
                status?: ("new" | "claimed" | "in_progress" | "resolved" | "dismissed")[] | null;
                /** @description null */
                attackCategory?: ("Benign" | "Botnet" | "Brute Force" | "DDoS" | "DoS" | "Infiltration" | "Port Scan" | "Web Attack")[] | null;
                /** @description null */
                requiresReview?: boolean | null;
                /** @description On combined_score */
                minScore?: number | null;
                /** @description null */
                maxScore?: number | null;
                /** @description Substring of source IP, destination IP, or matched rule id */
                search?: string | null;
                /** @description Restrict to one detection run */
                runId?: number | null;
                /** @description Filter by the verdict currently in force */
                verdict?: ("confirm_true_positive" | "mark_false_positive" | "mark_expected_activity" | "needs_investigation" | "escalate")[] | null;
                /** @description `me`: owned by the caller's demo user; `unassigned`: no owner */
                owner?: ("me" | "unassigned") | null;
                /** @description Earliest flow capture time, capture-local, e.g. 2018-02-14 12:00 */
                flowFrom?: string | null;
                /** @description Latest flow capture time; a date alone means the end of that day */
                flowTo?: string | null;
            };
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AlertSummary"][];
                        page: components["schemas"]["PageInfo"];
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The alert and its four evidence panels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignAlert: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description The alert after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description The verdict, its adjustment and its family effect */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Guardrail rejected the request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFeedbackHistory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verdict history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackHistory"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAlertNotes: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertNotes"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addAlertNote: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description The stored note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getScoreAdjustment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description original, requested, bound, actual, final */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreAdjustment"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    changeAlertStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description The alert's public UUID */
                alertRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description The alert after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                /** @description null */
                limit?: number;
                /** @description null */
                offset?: number;
                /** @description null */
                eventType?: ("LOGIN" | "LOGOUT" | "DETECTION_RUN" | "FEEDBACK" | "FEEDBACK_AMEND" | "GUARDRAIL_INTERVENTION" | "GUARDRAIL_REJECTION" | "SIMILAR_ALERT_LEARNING" | "ALERT_STATUS_CHANGE" | "ALERT_DUPLICATE" | "CONFIG_CHANGE" | "RULE_CREATE" | "RULE_UPDATE" | "MODEL_STATUS_CHANGE" | "EVALUATION_RUN")[] | null;
                /** @description null */
                actorId?: number | null;
                /** @description null */
                since?: string | null;
                /** @description null */
                until?: string | null;
            };
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEntryOut"][];
                        page: components["schemas"]["PageInfo"];
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGuardrailConfig: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailConfig"];
                };
            };
        };
    };
    updateGuardrailConfig: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardrailConfigUpdate"];
            };
        };
        responses: {
            /** @description The updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailConfig"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDashboardBreakdowns: {
        parameters: {
            query?: {
                /** @description How many top values to return per list */
                limit?: number;
            };
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Breakdowns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardBreakdowns"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    startDetectionRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DetectionRunRequest"];
            };
        };
        responses: {
            /** @description The run was accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionRunSummary"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getIpEntity: {
        parameters: {
            query?: {
                /** @description How many top values to return per list */
                limit?: number;
            };
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description An IPv4 or IPv6 address */
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The address's alerts, peers and ports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityIp"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEvaluationRuns: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EvaluationRunOut"][];
                        page: components["schemas"]["PageInfo"];
                    };
                };
            };
        };
    };
    getEvaluationRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description Evaluation run id, e.g. 20260912T032022Z */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arms, deltas and what the guardrails prevented */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparison"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEvaluationDetectionMetrics: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path: {
                /** @description Evaluation run id, e.g. 20260912T032022Z */
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-class metrics, saturation and I3 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDetectionMetrics"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEvaluationScenarios: {
        parameters: {
            query?: never;
            header?: {
                /** @description Role-switch stub (S18 replaces this with a real principal) */
                "X-Demo-Role"?: "security_analyst" | "system_admin" | "evaluator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EvaluationScenarioOut"][];
                        page: components["schemas"]["PageInfo"];
                    };
                };
            };
        };
    };
}
