/**
 * S14 — detection metrics for the newest run.
 *
 * The numbers are near-perfect, and the screen's job is to keep them from being read as more than
 * they are: the testbed caveat and the saturation sentence are as much a part of the page as the
 * per-class table, so they are asserted here rather than left to a screenshot.
 */

import { screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { jsonResponse, renderApp, stubFetch } from "../../../test/renderApp";
import { CLASS_NAMES, DETECTION, EVALUATOR, NO_RUNS_PAGE, RUNS_PAGE, RUN_ID } from "./fixtures";

function stubApi(runs: unknown = RUNS_PAGE, detection: unknown = DETECTION): void {
  stubFetch((request) => {
    const { pathname } = new URL(request.url);
    if (pathname === "/api/evaluation/runs") return jsonResponse(runs);
    if (pathname === `/api/evaluation/runs/${RUN_ID}/detection`) return jsonResponse(detection);
    return jsonResponse({ error: { code: "NOT_FOUND", message: `No stub for ${pathname}` } }, 404);
  });
}

const METRICS_PATH = "/evaluator/metrics";

describe("evaluator: detection metrics", () => {
  it("heads the page and shows the run's macro F1", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    expect(
      await screen.findByRole("heading", { level: 1, name: "Detection Metrics" }),
    ).toBeInTheDocument();
    expect(await screen.findByText("Macro F1")).toBeInTheDocument();
    expect(screen.getByText("0.988")).toBeInTheDocument();
  });

  it("links the KPI back to the run it measured", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    expect(await screen.findByRole("link", { name: RUN_ID })).toHaveAttribute(
      "href",
      `/evaluator/runs/${RUN_ID}`,
    );
  });

  it("shows a row for each of the eight classes", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    await screen.findByRole("link", { name: RUN_ID });
    for (const name of CLASS_NAMES) {
      expect(screen.getByRole("rowheader", { name })).toBeInTheDocument();
    }
    expect(screen.getAllByRole("rowheader")).toHaveLength(CLASS_NAMES.length + 5);
  });

  it("gives the headline F1 its testbed caveat", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    const caution = await screen.findByRole("note");
    expect(caution).toHaveTextContent(
      "The headline F1 is a property of this testbed dataset, where each attack class was generated by a single tool",
    );
    expect(caution).toHaveTextContent("it is not a claim about real-world traffic.");
  });

  it("says how saturated the flagged band is", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    expect(
      await screen.findByText(
        "975 of 996 flagged alerts share the maximum score, so a promotion among them can have nowhere to go.",
      ),
    ).toBeInTheDocument();
    expect(screen.getByText("97.9%")).toBeInTheDocument();
  });

  it("reports precision@k for each k, in order", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    await screen.findByRole("link", { name: RUN_ID });
    for (const k of ["10", "25", "50", "100", "200"]) {
      expect(screen.getByRole("rowheader", { name: k })).toBeInTheDocument();
    }
  });

  it("states I3's preservation rate as absent rather than as a pass", async () => {
    stubApi();
    renderApp(METRICS_PATH, { session: EVALUATOR });

    expect(
      await screen.findByRole("heading", {
        level: 2,
        name: "Signature-backed alerts (invariant I3)",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText("Preservation rate")).toBeInTheDocument();
    expect(screen.getByText(/I3 is guaranteed by S7's unit tests, not measured here/)).toBeInTheDocument();
  });

  it("says so when no run has been recorded", async () => {
    stubApi(NO_RUNS_PAGE);
    renderApp(METRICS_PATH, { session: EVALUATOR });

    expect(await screen.findByText("No evaluation runs recorded")).toBeInTheDocument();
    expect(screen.queryByRole("note")).toBeNull();
  });
});
